Imported Upstream version 0.9.9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -639,16 +639,17 @@ ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
 LIBOBJS
+plugindir
 GIO_DEFINES
 GIO_LIBS
 GIO_CFLAGS
 GCONF_DEFINES
-GCONF_LIBS
-GCONF_CFLAGS
 GCONF_SCHEMAS_INSTALL_FALSE
 GCONF_SCHEMAS_INSTALL_TRUE
 GCONF_SCHEMA_FILE_DIR
 GCONF_SCHEMA_CONFIG_SOURCE
+GCONF_LIBS
+GCONF_CFLAGS
 DBUS_LIBS
 DBUS_CFLAGS
 NSPR_LIBS
@@ -770,11 +771,12 @@ enable_option_checking
 enable_maintainer_mode
 enable_dependency_tracking
 with_xulrunner_sdk
+with_gconf
 with_gconf_source
 with_gconf_schema_file_dir
 enable_schemas_install
-with_gconf
 with_gio
+with_plugin_dir
 enable_caching
 '
       ac_precious_vars='build_alias
@@ -1437,13 +1439,16 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-xulrunner-sdk    Use xulrunner SDK for build
+  --with-xulrunner-sdk=path_to_sdk
+                          Path to xulrunner SDK for build
+                          --with-xulrunner-sdk=/path/to/sdk
+  --with-gconf            Use Gconf to store preferences
   --with-gconf-source=sourceaddress
                           Config database for installing schema files.
   --with-gconf-schema-file-dir=dir
                           Directory for installing schema files.
-  --with-gconf            Use Gconf to store preferences
   --with-gio              Use GIO for file I/O
+  --with-plugin-dir=dir   Directory where plugins are stored
 
 Some influential environment variables:
   CC          C compiler command
@@ -2392,7 +2397,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=gecko-mediaplayer
- VERSION=0.9.8
+ VERSION=0.9.9
 
 
 cat >>confdefs.h <<_ACEOF
@@ -9011,12 +9016,12 @@ if test -n "$GECKO_CFLAGS"; then
     pkg_cv_GECKO_CFLAGS="$GECKO_CFLAGS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libxul\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libxul") 2>&5
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libxul < 1.9.2\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libxul < 1.9.2") 2>&5
   ac_status=$?
   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "libxul" 2>/dev/null`
+  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "libxul < 1.9.2" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -9027,12 +9032,12 @@ if test -n "$GECKO_LIBS"; then
     pkg_cv_GECKO_LIBS="$GECKO_LIBS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libxul\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libxul") 2>&5
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libxul < 1.9.2\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libxul < 1.9.2") 2>&5
   ac_status=$?
   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "libxul" 2>/dev/null`
+  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "libxul < 1.9.2" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -9050,26 +9055,104 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libxul" 2>&1`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libxul < 1.9.2" 2>&1`
         else
-	        GECKO_PKG_ERRORS=`$PKG_CONFIG --print-errors "libxul" 2>&1`
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --print-errors "libxul < 1.9.2" 2>&1`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GECKO_PKG_ERRORS" >&5
 
 	{ $as_echo "$as_me:$LINENO: result: no" >&5
 $as_echo "no" >&6; }
-                { $as_echo "$as_me:$LINENO: WARNING: libxul not found, trying another" >&5
-$as_echo "$as_me: WARNING: libxul not found, trying another" >&2;}
+                { $as_echo "$as_me:$LINENO: WARNING: libxul < 1.9.2 not found, trying another" >&5
+$as_echo "$as_me: WARNING: libxul < 1.9.2 not found, trying another" >&2;}
 elif test $pkg_failed = untried; then
-	{ $as_echo "$as_me:$LINENO: WARNING: libxul not found, trying another" >&5
-$as_echo "$as_me: WARNING: libxul not found, trying another" >&2;}
+	{ $as_echo "$as_me:$LINENO: WARNING: libxul < 1.9.2 not found, trying another" >&5
+$as_echo "$as_me: WARNING: libxul < 1.9.2 not found, trying another" >&2;}
+else
+	GECKO_CFLAGS=$pkg_cv_GECKO_CFLAGS
+	GECKO_LIBS=$pkg_cv_GECKO_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	 { $as_echo "$as_me:$LINENO: libxul < 1.9.2 found" >&5
+$as_echo "$as_me: libxul < 1.9.2 found" >&6;}
+
+fi
+fi
+if test "$GECKO_CFLAGS" = ""; then
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for GECKO" >&5
+$as_echo_n "checking for GECKO... " >&6; }
+
+if test -n "$GECKO_CFLAGS"; then
+    pkg_cv_GECKO_CFLAGS="$GECKO_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libxul >= 1.9.2\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libxul >= 1.9.2") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GECKO_CFLAGS=`$PKG_CONFIG --cflags "libxul >= 1.9.2" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GECKO_LIBS"; then
+    pkg_cv_GECKO_LIBS="$GECKO_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libxul >= 1.9.2\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libxul >= 1.9.2") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GECKO_LIBS=`$PKG_CONFIG --libs "libxul >= 1.9.2" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libxul >= 1.9.2" 2>&1`
+        else
+	        GECKO_PKG_ERRORS=`$PKG_CONFIG --print-errors "libxul >= 1.9.2" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GECKO_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+                { $as_echo "$as_me:$LINENO: libxul >= 1.9.2 not found, trying another" >&5
+$as_echo "$as_me: libxul >= 1.9.2 not found, trying another" >&6;}
+elif test $pkg_failed = untried; then
+	{ $as_echo "$as_me:$LINENO: libxul >= 1.9.2 not found, trying another" >&5
+$as_echo "$as_me: libxul >= 1.9.2 not found, trying another" >&6;}
 else
 	GECKO_CFLAGS=$pkg_cv_GECKO_CFLAGS
 	GECKO_LIBS=$pkg_cv_GECKO_LIBS
         { $as_echo "$as_me:$LINENO: result: yes" >&5
 $as_echo "yes" >&6; }
 
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_NEW_XULRUNNER 1
+_ACEOF
+ { $as_echo "$as_me:$LINENO: libxul >= 1.9.2 found" >&5
+$as_echo "$as_me: libxul >= 1.9.2 found" >&6;}
 
 fi
 fi
@@ -9411,58 +9494,6 @@ fi
 
 
 
-  if test "x$GCONF_SCHEMA_INSTALL_SOURCE" = "x"; then
-    GCONF_SCHEMA_CONFIG_SOURCE=`gconftool-2 --get-default-source`
-  else
-    GCONF_SCHEMA_CONFIG_SOURCE=$GCONF_SCHEMA_INSTALL_SOURCE
-  fi
-
-
-# Check whether --with-gconf-source was given.
-if test "${with_gconf_source+set}" = set; then
-  withval=$with_gconf_source; GCONF_SCHEMA_CONFIG_SOURCE="$withval"
-fi
-
-
-
-  { $as_echo "$as_me:$LINENO: result: Using config source $GCONF_SCHEMA_CONFIG_SOURCE for schema installation" >&5
-$as_echo "Using config source $GCONF_SCHEMA_CONFIG_SOURCE for schema installation" >&6; }
-
-  if test "x$GCONF_SCHEMA_FILE_DIR" = "x"; then
-    GCONF_SCHEMA_FILE_DIR='$(sysconfdir)/gconf/schemas'
-  fi
-
-
-# Check whether --with-gconf-schema-file-dir was given.
-if test "${with_gconf_schema_file_dir+set}" = set; then
-  withval=$with_gconf_schema_file_dir; GCONF_SCHEMA_FILE_DIR="$withval"
-fi
-
-
-
-  { $as_echo "$as_me:$LINENO: result: Using $GCONF_SCHEMA_FILE_DIR as install directory for schema files" >&5
-$as_echo "Using $GCONF_SCHEMA_FILE_DIR as install directory for schema files" >&6; }
-
-  # Check whether --enable-schemas-install was given.
-if test "${enable_schemas_install+set}" = set; then
-  enableval=$enable_schemas_install; case ${enableval} in
-       yes|no) ;;
-       *) { { $as_echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-schemas-install" >&5
-$as_echo "$as_me: error: bad value ${enableval} for --enable-schemas-install" >&2;}
-   { (exit 1); exit 1; }; } ;;
-      esac
-fi
-
-   if test "$enable_schemas_install" != no; then
-  GCONF_SCHEMAS_INSTALL_TRUE=
-  GCONF_SCHEMAS_INSTALL_FALSE='#'
-else
-  GCONF_SCHEMAS_INSTALL_TRUE='#'
-  GCONF_SCHEMAS_INSTALL_FALSE=
-fi
-
-
-
 # Check whether --with-gconf was given.
 if test "${with_gconf+set}" = set; then
   withval=$with_gconf;
@@ -9538,7 +9569,59 @@ else
 	GCONF_LIBS=$pkg_cv_GCONF_LIBS
         { $as_echo "$as_me:$LINENO: result: yes" >&5
 $as_echo "yes" >&6; }
-	GCONF_DEFINES="-DHAVE_GCONF"
+
+  if test "x$GCONF_SCHEMA_INSTALL_SOURCE" = "x"; then
+    GCONF_SCHEMA_CONFIG_SOURCE=`gconftool-2 --get-default-source`
+  else
+    GCONF_SCHEMA_CONFIG_SOURCE=$GCONF_SCHEMA_INSTALL_SOURCE
+  fi
+
+
+# Check whether --with-gconf-source was given.
+if test "${with_gconf_source+set}" = set; then
+  withval=$with_gconf_source; GCONF_SCHEMA_CONFIG_SOURCE="$withval"
+fi
+
+
+
+  { $as_echo "$as_me:$LINENO: result: Using config source $GCONF_SCHEMA_CONFIG_SOURCE for schema installation" >&5
+$as_echo "Using config source $GCONF_SCHEMA_CONFIG_SOURCE for schema installation" >&6; }
+
+  if test "x$GCONF_SCHEMA_FILE_DIR" = "x"; then
+    GCONF_SCHEMA_FILE_DIR='$(sysconfdir)/gconf/schemas'
+  fi
+
+
+# Check whether --with-gconf-schema-file-dir was given.
+if test "${with_gconf_schema_file_dir+set}" = set; then
+  withval=$with_gconf_schema_file_dir; GCONF_SCHEMA_FILE_DIR="$withval"
+fi
+
+
+
+  { $as_echo "$as_me:$LINENO: result: Using $GCONF_SCHEMA_FILE_DIR as install directory for schema files" >&5
+$as_echo "Using $GCONF_SCHEMA_FILE_DIR as install directory for schema files" >&6; }
+
+  # Check whether --enable-schemas-install was given.
+if test "${enable_schemas_install+set}" = set; then
+  enableval=$enable_schemas_install; case ${enableval} in
+       yes|no) ;;
+       *) { { $as_echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-schemas-install" >&5
+$as_echo "$as_me: error: bad value ${enableval} for --enable-schemas-install" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      esac
+fi
+
+   if test "$enable_schemas_install" != no; then
+  GCONF_SCHEMAS_INSTALL_TRUE=
+  GCONF_SCHEMAS_INSTALL_FALSE='#'
+else
+  GCONF_SCHEMAS_INSTALL_TRUE='#'
+  GCONF_SCHEMAS_INSTALL_FALSE=
+fi
+
+
+ GCONF_DEFINES="-DHAVE_GCONF"
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_GCONF 1
 _ACEOF
@@ -9640,6 +9723,16 @@ fi
 fi
 
 
+
+# Check whether --with-plugin_dir was given.
+if test "${with_plugin_dir+set}" = set; then
+  withval=$with_plugin_dir; plugindir=$withval
+else
+  plugindir='$(libdir)/mozilla/plugins'
+fi
+
+
+
 # Check whether --enable-caching was given.
 if test "${enable_caching+set}" = set; then
   enableval=$enable_caching; usecache=$enableval
@@ -9651,6 +9744,8 @@ fi
 if test $usecache != yes; then
 	GECKO_CFLAGS="$GECKO_CFLAGS -DDISABLE_CACHE"
 fi
+
+
 
 ac_config_files="$ac_config_files Makefile gecko-mediaplayer.spec src/Makefile src/libgmlib/Makefile po/Makefile.in"
 
